### ISSUE TITLE
Value of autoStart from config is ignored

### ISSUE THREAD

**Issue by augustl** [padcom/grails-routing#44]
In commit c82d50f0bb7f251cfe1e36c6bec6c979b585c94d, a change was made that disabled autoStartup at plugin init time, and deferred to a manual start in doWithDynamicMethods.

This startup procedure checks the config for an "autoStartup" flag so you can disable auto start if you want, and manually start the app later. But this check is bugged.

```groovy
def config = application.config.grails.routing
		
if (config.grails.routing.autoStartup ?: true) {
    def camelContextId = config.camelContextId ?: 'camelContext'
    application.mainContext.getBean(camelContextId).start()
}
```

If `application.config.grails.routing.grails.routing.autoStartup` is set to false, the whole statement will evaluate to true anyway:

```groovy
false ?: true // Returns true
````

A better check would be something like:

```groovy
if (application.config.grails.routing.grails.routing.autoStartup != false) {
    def camelContextId = config.camelContextId ?: 'camelContext'
    application.mainContext.getBean(camelContextId).start()
}
```

That way, you can set autoStartup to `false` in config, but if it's not set, it will start up automatically.

As an aside, it would probably be better if the config was `application.config.grails.routing.autoStartup` instead of `application.config.grails.routing.grails.routing.autoStartup`. This bug seems to have been introduced in commit 40a241b2cba377d1237564e2374f1208b5fb3708.

**Comment by gutsal-arsen** [comment]
@augustl sorry man. That too waaaaayyy too long to release it on grails central. Seems I've just done it. 1.3.3 should be accessible soon. Seems that project gets out of contributors and I just don't have time to work on it. Basically  I'm looking for ppl who is still interested and would contribute.

**Comment by augustl** [comment]
Just verified that this works in 1.4.0, closing. Thanks :)
